### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by sampie** [proteomics-mayu/mayu#2] opened 2017-02-18 08:45 UTC
Maiu (1.08) crashes for following error:
Illegal division by zero at lib/MayuTools.pm line 609.

I am running Mayu with following parameters:
Mayu.pl -A iProfet.pep.xml -C irt_Q7M135_trypsin_human-DECOY.fasta -E DECOY_ -G 0.01 -H 51 -I 2 -P protFDR=0.01:t

**Comment by sampie** [comment] 2017-02-18 08:55
GIT version of Maiu has changed a bit, as it gives different line:
Illegal division by zero at lib/MayuTools.pm line 610.

**Comment by lcb** [comment] 2017-02-19 07:25
Can confirm with provided example data:
`./Mayu.pl -verbose -B example.csv -C tardecdb.fa -E DECOY_ -G 0.01 -H 51 -I 2 -P protFDR00.01:t`
...
`Illegal division by zero at lib/MayuTools.pm line 609.`

**Comment by lcb** [comment] 2017-02-21 18:55
Dear @sampie 
I could make it work on the example data by using
`./Mayu.pl -verbose -B example.csv -C tardecdb.fa -E rev_ -G 0.01 -H 51 -I 2 -P protFDR00.01:t`

the problem was the -E flag was set to DECOY_ although the fasta database contained decoy entries with "rev_". Can you please check that the decoy label is correct?
If so and the problem is still there, can you post your data so I can debug?

**Comment by sampie** [comment] 2017-02-22 09:41
Dear @lcb ,

Thank you for taking a look at this issue!

The DECOY_ prefix is correct for the data I am using. However, I noticed that preceding xinteract program is giving warnings like "WARNING: Mixture model quality test failed for charge..". Perhaps in this case the xinteract is not producing good quality output.

Unfortunately the data is not owned by me and I am not allowed to hand it over. However, I produced a new analysis run against the data with using different search sequence database. In this case there were no warnings from xinteract and there were also no problems with Mayu.

**Comment by lcb** [comment] 2017-02-23 20:07
Dear @sampie 

Oh yes I know the problem of data security, especially for unpublished data :)

Well, I remember we had the rule of thumb that the
"Mixture model quality test failed for charge.." error can occur for higher charges (4+) but it should not appear for 2+ or 3+, that was a sign for a bad run (or bad parameters).

Anyway so it was not really a problem of Mayu but rather of bad input, and I think nobody really has time to dig deeper into this problem, so I am going to close this thread.

**Closed as completed by lcb** 2017-02-23 20:07 UTC

**Comment by vidyavenkatraman** [comment] 2019-06-27 05:52
I am having this same error: Illegal division by zero at /hpc/apps/TPP/5.2.0/bin/../lib/Mayu/MayuTools.pm line 609.

My command is : Mayu.pl -A /scratch/vaibhavv/iphronesis/platform_workspace/jobs/SJOB2405/interprophetparser/2405_vv.iprophet.pep.xml -C /hpc/home/svc-optrahpcportal/iphronesis/reference_files/Databases/UP_Human_Rev_Canonical_20180506_DECOY.fasta -E DECOY -G 0.01 -H 151 -I 2 -P protFDR=0.01:t -verbose

I did double check the decoy is denoted correctly. I also saw that my xinteract results from Tandem & Comet do have +2 & +3 charges. I am happy to share the files via Box. 

Please let me know your thoughts!
